### ISSUE TITLE
[feat] jiemao/purrrr toggle for "open in app"

### ISSUE THREAD

**Issue by dumbmoron** [imputnet/meow-issues#6]
**describe the feature you'd like to see**
- a way to toggle between android/ios and purrrr/jiemao links for qr code
- a way to toggle (or select somehow) between purrrr/jiemao links for direct link on mobile

**describe why this feature would be useful**
we got many apps and many phones unfortunately

**Comment by yeeterlol** [comment]
hellopurr:// is the protocol url for purrr if you need it

**Comment by dumbmoron** [comment]
> hellopurr:// is the protocol url for purrr if you need it

yea but the app does not support any deeplinks yet lol

**Comment by yeeterlol** [comment]
> > hellopurr:// is the protocol url for purrr if you need it
> 
> yea but the app does not support any deeplinks yet lol

yeah just found out right now after i posted that

**Comment by dumbmoron** [comment]
added in v1.1 ![Image](https://github.com/imputnet/meow-issues/assets/136796770/3bc61435-b0aa-427f-8d90-49bbf9abf6e7)
