### ISSUE TITLE
[bug] searchbar is not working on safari in iPadOS 15

### ISSUE THREAD

**Issue by dumbmoron** [imputnet/meow-issues#9]
from @/syna.kil on discord

### bug description
when i select the searchbar (you cant really see it in the video but i promise i selected it) it will not let me type. at one point i managed to input "e" but i cannot do it again. 

### screenshots
https://github.com/imputnet/meow-issues/assets/136796770/c613559a-a032-49c9-a371-4bf1bf443dee

### platform
ipad, iPadOS 15

**Comment by lostdusty** [comment]
Same issue here, iPadOS 15.4, iPad Air 2

**Comment by dumbmoron** [comment]
fixed in latest version
